### ISSUE TITLE
Distributed mode not working in AWS EC2 instance using cookbook

### ISSUE THREAD

**Issue by muthukumarkubendran** [fgimenez/orientdb-cookbook#14]
Hi,

I'm currently running into the below issue where setting up orientdb on AWS ec2 instance using chef cookbook.I'm using the version community edition 2.1.8... I followed the reference cookbook from https://github.com/fgimenez/orientdb-cookbook.

nodename genererated automatically

<handler class="com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin">
            <parameters>
                <parameter name="nodeName" value="10.94.77.214_160120123938" />
                <parameter name="enabled" value="true"/>
                <parameter name="configuration.db.default"
                           value="${ORIENTDB_HOME}/config/default-distributed-db-config.json"/>
                <parameter name="configuration.hazelcast" value="${ORIENTDB_HOME}/config/hazelcast.xml"/>
            </parameters>
        </handler>

Here is the error message from log file

2016-01-20 12:48:31:388 INFO  Installing GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]Exception in thread "main" com.orientechnologies.orient.core.exception.OConfigurationException: Illegal node name '10.94.77.214_160120123938'. '.' is not allowed in node name
        at com.orientechnologies.orient.server.distributed.ODistributedAbstractPlugin.config(ODistributedAbstractPlugin.java:119)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.config(OHazelcastPlugin.java:116)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:978)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:346)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)

Here is the config from orientdb-server-config.xml

 
    <handler class="com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin">
            <parameters>
                <parameter name="nodeName" value="<%= node['orientdb']['hazelcast']['nodeName']%>" />
                <parameter name="enabled" value="<%= node['orientdb']['hazelcast']['enabled']%>"/>
                <parameter name="configuration.db.default"
                           value="${ORIENTDB_HOME}/config/default-distributed-db-config.json"/>
                <parameter name="configuration.hazelcast" value="${ORIENTDB_HOME}/config/hazelcast.xml"/>
            </parameters>
        </handler>
    
Here is the detailed log from orientdb-err.log

2016-01-20 13:41:11:895 INFO  Installing GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]Exception in thread "main" com.orientechnologies.orient.core.exception.OConfigurationException: Illegal node name '10.94.77.111_160120133340'. '.' is not allowed in node name
        at com.orientechnologies.orient.server.distributed.ODistributedAbstractPlugin.config(ODistributedAbstractPlugin.java:119)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.config(OHazelcastPlugin.java:116)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:978)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:346)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)

2016-01-20 13:41:32:435 WARNI Distributed server is not yet ONLINE (status=OFFLINE), reject incoming connection from /10.94.77.111:60726. If you are trying to shutdown the server, please kill the process [OServerNetworkListener]
2016-01-20 13:46:27:892 WARNI Distributed server is not yet ONLINE (status=OFFLINE), reject incoming connection from /10.94.77.111:60828. If you are trying to shutdown the server, please kill the process [OServerNetworkListener]log.OLogManager log
INFO: Loading configuration from: /opt/orientdb/config/orientdb-server-config.xml...
Jan 20, 2016 1:41:32 PM com.orientechnologies.common.log.OLogManager log
SEVERE: Error on connecting to 0.0.0.0:2424
com.orientechnologies.orient.enterprise.channel.binary.ONetworkProtocolException: Cannot read protocol version from remote server ip-10-94-77-111.kdc.capitalone.com/10.94.77.111:2424: java.io.EOFException
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:99)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:62)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClientSynch.<init>(OChannelBinaryAsynchClientSynch.java:36)
        at com.orientechnologies.orient.server.OServerShutdownMain.connect(OServerShutdownMain.java:107)
        at com.orientechnologies.orient.server.OServerShutdownMain.main(OServerShutdownMain.java:139)

Jan 20, 2016 1:41:32 PM com.orientechnologies.common.log.OLogManager log
SEVERE: Error on connecting to 0.0.0.0:2425
java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:83)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:62)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClientSynch.<init>(OChannelBinaryAsynchClientSynch.java:36)
        at com.orientechnologies.orient.server.OServerShutdownMain.connect(OServerShutdownMain.java:107)
        at com.orientechnologies.orient.server.OServerShutdownMain.main(OServerShutdownMain.java:139)

Jan 20, 2016 1:41:32 PM com.orientechnologies.common.log.OLogManager log
SEVERE: Error on connecting to 0.0.0.0:2426
java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:83)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:62)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClientSynch.<init>(OChannelBinaryAsynchClientSynch.java:36)
        at com.orientechnologies.orient.server.OServerShutdownMain.connect(OServerShutdownMain.java:107)
        at com.orientechnologies.orient.server.OServerShutdownMain.main(OServerShutdownMain.java:139)

**Comment by muthukumarkubendran** [comment]
Hi @fgimenez

Could you please help me figure out this issue. Currently I'm running orientdb in standalone mode by 
default['orientdb']['hazelcast']['enabled'] changing this config to false. If I enable this to true, I'm getting the error above that states node name is invalid.

Also I looked at the orientdb documentation, they stated that I should use dserver.sh file to enable distributed mode... however this file is not located on the orientdb cookbook template folder... am I missing something here... please let me know.


Regards
Muthu

**Comment by fgimenez** [comment]
Hi @muthukumarkubendran from the trace, very difficult to read btw ;), it seemsthat there is a problem with the node name, don't know how are you appliying the recipe but you should be able to easily override the ['orientdb']['hazelcast']['nodeName'] attribute.

Cheers

**Comment by muthukumarkubendran** [comment]
Hi @fgimenez, Thank you for the response. I'm running this cookbook using cloud formation template where it bootstrap orientdb cookbbok from chef server. Can I use this cook book in AWS EC2 instance since multicast is not supported by most of cloud. 

I'm having a fundamental question on setting up distributed environment, do I have to run this cookbook on 2 servers. what I mean is that  orientdb should be installed on 2 servers to make use of distributed environment, or if I run this cookbook, it will install orientdb on one ec2 instance and when the new node is added to the cluster, will it automatically install orientdb and  copy databases folder. In general, what are the prerequisites for enabling distributed environment.

**Comment by fgimenez** [comment]
@muthukumarkubendran according to [1] an `aws` element is missing in `config/hazelcast.xml`, and probably the `hazelcast-cloud.jar` library under the lib directory. I'll prepare a PR to add those and the required attributes, stay tunned.

Thanks,

[1] http://orientdb.com/docs/2.0/orientdb.wiki/Distributed-Configuration.html#amazon-ec2

**Comment by muthukumarkubendran** [comment]
@fgimenez, 

Thanks for inputs, I will wait for your changes.

Meanwhile, I updated hazelcast.xml and added new hazelcast-cloud.jar in lib folder, and dealing with the below issue...

Connection timed out and Error on starting distributed plugin. Please let me know if you find any resolution.

log statements below...

2016-01-25 13:08:39:906 INFO  [10.94.77.192]:2434 [orientdb] [3.5.3] Backpressure is disabled [OperationService]
2016-01-25 13:08:39:932 INFO  [10.94.77.192]:2434 [orientdb] [3.5.3] Starting with 2 generic operation threads and 2 partition operation threads. [ClassicOperationExecutor]
2016-01-25 13:08:40:450 INFO  [10.94.77.192]:2434 [orientdb] [3.5.3] Hazelcast 3.5.3 (20151011 - 64c663a) starting at Address[10.94.77.192]:2434 [system]
2016-01-25 13:08:40:454 INFO  [10.94.77.192]:2434 [orientdb] [3.5.3] Copyright (c) 2008-2015, Hazelcast, Inc. All Rights Reserved. [system]
2016-01-25 13:08:40:457 INFO  [10.94.77.192]:2434 [orientdb] [3.5.3] Creating AWSJoiner [Node]
2016-01-25 13:08:40:472 INFO  [10.94.77.192]:2434 [orientdb] [3.5.3] Address[10.94.77.192]:2434 is STARTING [LifecycleService][10.94.77.192]:2434 [orientdb] [3.5.3] Connection timed out
java.net.ConnectException: Connection timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)


2016-01-25 13:20:50:490 SEVER [10.94.77.192]:2434 [orientdb] [3.5.3] Could not join cluster in 300000 ms. Shutting down now! [Node]
2016-01-25 13:20:50:491 INFO  [10.94.77.192]:2434 [orientdb] [3.5.3] Address[10.94.77.192]:2434 is SHUTTING_DOWN [LifecycleService]
2016-01-25 13:20:50:491 WARNI [10.94.77.192]:2434 [orientdb] [3.5.3] Terminating forcefully... [Node]
2016-01-25 13:20:50:491 INFO  [10.94.77.192]:2434 [orientdb] [3.5.3] Shutting down connection manager... [Node]
2016-01-25 13:20:50:500 INFO  [10.94.77.192]:2434 [orientdb] [3.5.3] Shutting down node engine... [Node]
2016-01-25 13:20:50:507 INFO  [10.94.77.192]:2434 [orientdb] [3.5.3] Destroying node NodeExtension. [NodeExtension]
2016-01-25 13:20:50:511 INFO  [10.94.77.192]:2434 [orientdb] [3.5.3] Hazelcast Shutdown is completed in 20 ms. [Node]
2016-01-25 13:20:50:511 INFO  [10.94.77.192]:2434 [orientdb] [3.5.3] Address[10.94.77.192]:2434 is SHUTDOWN [LifecycleService][node1453745985616] Error on starting distributed plugin
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@796065aa rejected from java.util.concurrent.ScheduledThreadPoolExecutor@28a6301f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 719]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)

**Comment by rayrod2030** [comment]
@muthukumarkubendran Is the security group for your cluster open on port 2434 to itself?  Meaning can all the nodes talk to each other on port 2434?

**Comment by fgimenez** [comment]
@muthukumarkubendran there's a new version of the cookbook uploaded to supermarket which adds AWS EC2 support for distributed mode according to the documentation, please check if it works for you, given that you have reviewed also @rayrod2030 suggestion.

**Comment by muthukumarkubendran** [comment]
Thanks @fgimenez. I'm currently setting up the instances on AWS with the new cookbooks, Is it possible to  setup distributed mode using single ec2 instance.Meaning that only one node is created  and acts as distributed environment. is that possible?

**Comment by fgimenez** [comment]
@muthukumarkubendran yes, you just need to set the `node['orientdb']['hazelcast']['network']['join']['mode']` attribute to `aws` and all the `node['orientdb']['hazelcast']['network']['join']['aws']` ones to the values specific to your aws account.

**Comment by fgimenez** [comment]
Closing this, the cookbook now generates config files according to upstream's instructions.
